spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/products-api
    password: '242824'
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
